let inventoryRows=[];const q=new URLSearchParams(location.search);const characterId=q.get('id');
const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
const equipmentSlots=['Head','Neck','Chest','Hands','Legs','Feet','Main Hand','Off Hand','Ring 1','Ring 2','Artifact'];
const showItem=item=>{const d=document.getElementById('item-detail');d.innerHTML=`${item.image_url?`<img src="${esc(item.image_url)}" alt="${esc(item.name)}">`:''}<h3>${esc(item.name)}</h3><p class="item-rarity">${esc(item.rarity||'Common')} ${esc(item.item_type||'Item')}</p><p>${esc(item.description||'No item description.')}</p><p>Quantity: ${item.quantity||1}</p>`};
const renderInventory=filter=>{const grid=document.getElementById('inventory-grid');const rows=filter==='all'?inventoryRows:inventoryRows.filter(r=>(r.items?.item_type||'').toLowerCase().includes(filter));document.getElementById('inventory-count').textContent=`${inventoryRows.length} Item${inventoryRows.length===1?'':'s'}`;if(!rows.length){grid.innerHTML='<div class="inventory-empty">No items in this category.</div>';return}grid.innerHTML=rows.map((r,i)=>`<button class="inventory-slot" data-item-index="${inventoryRows.indexOf(r)}" title="${esc(r.items?.name||'Item')}">${r.items?.image_url?`<img src="${esc(r.items.image_url)}" alt="">`:'◇'}<span>${r.quantity||1}</span></button>`).join('')};
window.addEventListener('dnd:navigation-ready',async event=>{
 const {session}=event.detail;if(!characterId){location.href='index.html';return}
 const {data:c,error}=await window.DND.client.from('characters').select('*').eq('id',characterId).eq('user_id',session.user.id).single();if(error){document.getElementById('sheet-loading').textContent=error.message;return}
 const portrait=c.portrait_url||'../../assets/images/shared/character-placeholder.png';document.getElementById('sheet-portrait').src=portrait;document.getElementById('sheet-display-image').src=portrait;
 const set=(id,v)=>document.getElementById(id).textContent=v??'—';set('sheet-name',c.name);set('sheet-title',c.title||'');set('sheet-race',c.race||'Unknown Race');set('sheet-alignment',c.alignment||'Unaligned');set('sheet-level',c.level||1);set('sheet-class',c.class||'Adventurer');set('sheet-xp',c.experience||0);set('sheet-next-xp',c.experience_to_next||1000);set('sheet-background',c.background||'Unknown');set('sheet-current-hp',c.current_hp??0);set('sheet-max-hp',c.max_hp??0);set('sheet-mana',`${c.current_mana??0} / ${c.max_mana??0}`);set('sheet-gold',c.gold??0);set('sheet-silver',c.silver??0);set('sheet-copper',c.copper??0);set('sheet-biography',c.biography||'No biography has been added.');
 document.getElementById('xp-meter').style.width=`${Math.min(100,Math.round(((c.experience||0)/(c.experience_to_next||1000))*100))}%`;
 const attrs=[['Strength',c.strength],['Dexterity',c.dexterity],['Constitution',c.constitution],['Intelligence',c.intelligence],['Wisdom',c.wisdom],['Charisma',c.charisma]];document.getElementById('attribute-list').innerHTML=attrs.map(([n,v])=>`<div class="attribute-row"><span>${n}</span><strong>${v??10}</strong></div>`).join('');
 document.getElementById('equipment-grid').innerHTML=equipmentSlots.map(s=>`<div class="equipment-slot">${s}</div>`).join('');
 const {data:inv}=await window.DND.client.from('inventory').select('id,quantity,items(id,name,rarity,item_type,image_url,description)').eq('character_id',characterId);inventoryRows=inv||[];renderInventory('all');
 document.getElementById('inventory-grid').addEventListener('click',e=>{const b=e.target.closest('[data-item-index]');if(b)showItem({...inventoryRows[Number(b.dataset.itemIndex)].items,quantity:inventoryRows[Number(b.dataset.itemIndex)].quantity})});
 document.querySelector('.inventory-filters').addEventListener('click',e=>{const b=e.target.closest('[data-filter]');if(!b)return;document.querySelectorAll('[data-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderInventory(b.dataset.filter)});
 document.getElementById('edit-character').addEventListener('click',()=>location.href=`create.html?id=${characterId}`);
 document.getElementById('delete-character').addEventListener('click',async()=>{const ok=await window.DNDModal.confirm({type:'danger',kicker:'Character Management',title:'Delete Character',message:`Delete ${c.name}?\n\nThis removes the character and linked character records. This cannot be undone.`,confirmText:'Delete Character',cancelText:'Keep Character',focusCancel:true});if(!ok)return;const {error:del}=await window.DND.client.from('characters').delete().eq('id',characterId).eq('user_id',session.user.id);if(del){window.DND.toast(del.message,'error');return}location.href='index.html'});
 document.getElementById('sheet-loading').hidden=true;document.getElementById('character-sheet').hidden=false;
});
