(() => {
  const $=s=>document.querySelector(s),esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
  const slots=['Head','Neck','Chest','Hands','Legs','Feet','Main Hand','Off Hand','Ring 1','Ring 2','Artifact','Backpack'];
  const bonusFields=['strength','dexterity','constitution','intelligence','wisdom','charisma','hp','mana'];
  const BUCKET='item-icons',MAX_BYTES=5*1024*1024,MIN_SIZE=128,MAX_SIZE=1024,RECOMMENDED=256;
  let items=[],selectedFile=null,selectedFileInfo=null,objectUrl=null,originalImageUrl=null;
  const slug=s=>String(s||'').trim().toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
  const hasBonuses=i=>bonusFields.some(k=>Number(i[`${k}_bonus`])!==0);
  const incomplete=i=>!i.item_key||!i.name||!i.image_url||(!i.equip_slot&&['weapon','armor'].includes(String(i.item_type).toLowerCase()))||!i.description;
  const checkedSlots=()=>[...document.querySelectorAll('[data-allowed-slot]:checked')].map(x=>x.value);

  function updateSummary(){ $('#catalog-total').textContent=items.length;$('#catalog-equippable').textContent=items.filter(i=>i.equip_slot||(i.allowed_slots||[]).length).length;$('#catalog-bonuses').textContent=items.filter(hasBonuses).length;$('#catalog-incomplete').textContent=items.filter(incomplete).length }
  function render(){const search=$('#catalog-search').value.trim().toLowerCase(),type=$('#catalog-type').value.toLowerCase(),setup=$('#catalog-setup').value;const rows=items.filter(i=>{const text=[i.name,i.item_key,i.item_type,i.equip_slot].join(' ').toLowerCase();return(!search||text.includes(search))&&(type==='all'||String(i.item_type).toLowerCase()===type)&&(setup==='all'||(setup==='incomplete'?incomplete(i):!incomplete(i)))});$('#catalog-list').innerHTML=rows.length?rows.map(i=>`<button type="button" class="catalog-item ${incomplete(i)?'incomplete':'ready'}" data-edit-item="${i.id}">${i.image_url?`<img src="${esc(i.image_url)}" alt="">`:'<span>◇</span>'}<div><strong>${esc(i.name)}</strong><small>${esc(i.rarity||'Common')} • ${esc(i.item_type||'Item')}${i.equip_slot?` • ${esc(i.equip_slot)}`:''}</small><em>${incomplete(i)?'Needs Setup':hasBonuses(i)?'Ready • Bonuses Defined':'Ready'}</em></div></button>`).join(''):'<p class="catalog-empty">No Items match these filters.</p>'}
  async function load(){const {data,error}=await window.DND.client.from('items').select('*').order('name');if(error){$('#catalog-list').innerHTML=`<p class="catalog-error">${esc(error.message)}</p>`;return}items=data||[];updateSummary();render()}

  function clearObjectUrl(){if(objectUrl){URL.revokeObjectURL(objectUrl);objectUrl=null}}
  function setValidation(message,type='info'){const box=$('#upload-validation');box.className=`upload-validation ${type}`;box.textContent=message||''}
  function showExistingImage(url){clearObjectUrl();selectedFile=null;selectedFileInfo=null;originalImageUrl=url||null;$('#item-image').value=url||'';$('#upload-placeholder').hidden=Boolean(url);$('#upload-preview').hidden=!url;$('#remove-item-image').hidden=!url;if(url){$('#upload-preview-image').src=url;$('#upload-file-name').textContent='Current Item icon';$('#upload-file-details').textContent='Stored in Supabase Storage';$('#upload-status').textContent='Image already uploaded';setValidation('Select or drop a new image to replace the current icon.','info')}else setValidation('PNG or WebP. Square image required. 256 × 256 px is recommended.','info');updatePreview()}
  async function inspectFile(file){if(!file)return;clearObjectUrl();selectedFile=null;selectedFileInfo=null;const allowed=['image/png','image/webp'];if(!allowed.includes(file.type)){setValidation('Unsupported file type. Select a PNG or WebP image.','error');return}if(file.size>MAX_BYTES){setValidation('Image is larger than 5 MB. Select a smaller file.','error');return}objectUrl=URL.createObjectURL(file);const image=new Image();image.onload=()=>{const width=image.naturalWidth,height=image.naturalHeight;const issues=[];if(width!==height)issues.push('The image must be square.');if(width<MIN_SIZE||height<MIN_SIZE)issues.push('The image is smaller than 128 × 128 px.');if(width>MAX_SIZE||height>MAX_SIZE)issues.push('The image is larger than 1024 × 1024 px.');if(issues.length){setValidation(issues.join(' '),'error');clearObjectUrl();return}selectedFile=file;selectedFileInfo={width,height};$('#upload-placeholder').hidden=true;$('#upload-preview').hidden=false;$('#remove-item-image').hidden=false;$('#upload-preview-image').src=objectUrl;$('#upload-file-name').textContent=file.name;$('#upload-file-details').textContent=`${width} × ${height} px • ${(file.size/1024).toFixed(0)} KB • ${file.type.replace('image/','').toUpperCase()}`;$('#upload-status').textContent='Image will upload when the Item is saved';setValidation(width===RECOMMENDED&&height===RECOMMENDED?'Image meets the recommended 256 × 256 px standard.':'Image is valid. 256 × 256 px is recommended for consistent Item icons.','success');updatePreview()};image.onerror=()=>setValidation('The selected image could not be read.','error');image.src=objectUrl}
  async function uploadSelected(itemKey){if(!selectedFile)return $('#item-image').value||null;const ext=selectedFile.type==='image/webp'?'webp':'png';const path=`${itemKey}/icon.${ext}`;$('#upload-status').textContent='Uploading image...';const {error}=await window.DND.client.storage.from(BUCKET).upload(path,selectedFile,{cacheControl:'3600',upsert:true,contentType:selectedFile.type});if(error)throw error;const {data}=window.DND.client.storage.from(BUCKET).getPublicUrl(path);if(!data?.publicUrl)throw new Error('The uploaded image URL could not be created.');$('#item-image').value=data.publicUrl;$('#upload-status').textContent='Image uploaded';return data.publicUrl}
  async function removeOldObject(url){if(!url||!url.includes(`/storage/v1/object/public/${BUCKET}/`))return;const marker=`/storage/v1/object/public/${BUCKET}/`;const path=decodeURIComponent(url.split(marker)[1]||'');if(path)await window.DND.client.storage.from(BUCKET).remove([path])}

  function updatePreview(){const name=$('#item-name').value||'Item Preview',rarity=$('#item-rarity').value,type=$('#item-type').value,slot=$('#item-slot').value,image=objectUrl||$('#item-image').value.trim();$('#editor-preview-name').textContent=name;$('#editor-preview-meta').textContent=[rarity,type,slot].filter(Boolean).join(' • ');$('#editor-image-preview').src=image||'../../assets/images/shared/character-placeholder.png';const effects=[];[['STR','strength'],['DEX','dexterity'],['CON','constitution'],['INT','intelligence'],['WIS','wisdom'],['CHA','charisma'],['HP','hp'],['Mana','mana']].forEach(([label,key])=>{const value=Number($(`#bonus-${key}`).value)||0;if(value)effects.push(`<span>${label} <b>${value>0?'+':''}${value}</b></span>`)});$('#editor-preview-effects').innerHTML=effects.length?effects.join(''):'<small>No bonuses defined.</small>'}
  function openEditor(item=null){clearObjectUrl();selectedFile=null;selectedFileInfo=null;$('#catalog-form').hidden=false;$('#editor-title').textContent=item?'Edit Item':'Create Item';$('#item-id').value=item?.id||'';$('#item-name').value=item?.name||'';$('#item-key').value=item?.item_key||'';$('#item-rarity').value=item?.rarity||'Common';$('#item-type').value=item?.item_type||'Item';$('#item-slot').value=item?.equip_slot||'';$('#item-stackable').value=String(Boolean(item?.stackable));$('#item-max-stack').value=item?.max_stack||1;$('#item-description').value=item?.description||'';$('#item-notes').value=item?.notes||'';$('#item-grid-width').value=item?.grid_width||1;$('#item-grid-height').value=item?.grid_height||1;$('#item-can-rotate').value=String(item?.can_rotate!==false);$('#item-pocket-eligible').value=String(Boolean(item?.pocket_eligible));$('#item-is-backpack').value=String(Boolean(item?.is_backpack));$('#item-backpack-columns').value=item?.backpack_columns||4;$('#item-backpack-rows').value=item?.backpack_rows||4;$('#backpack-size-fields').hidden=!item?.is_backpack;bonusFields.forEach(k=>$(`#bonus-${k}`).value=item?.[`${k}_bonus`]||0);document.querySelectorAll('[data-allowed-slot]').forEach(x=>x.checked=(item?.allowed_slots||[]).includes(x.value));$('#catalog-delete').hidden=!item;showExistingImage(item?.image_url||'');$('#catalog-form').scrollIntoView({behavior:'smooth',block:'start'})}
  function closeEditor(){clearObjectUrl();$('#catalog-form').hidden=true}
  async function save(e){e.preventDefault();const id=$('#item-id').value,key=slug($('#item-key').value||$('#item-name').value);if(!key){window.DND.toast('Item Key is required.','error');return}if(!selectedFile&&!$('#item-image').value){setValidation('Upload an Item icon before saving.','error');return}const saveButton=e.submitter;saveButton.disabled=true;saveButton.textContent='Saving...';try{const imageUrl=await uploadSelected(key);const payload={name:$('#item-name').value.trim(),item_key:key,rarity:$('#item-rarity').value,item_type:$('#item-type').value,equip_slot:$('#item-slot').value||null,allowed_slots:checkedSlots(),image_url:imageUrl,description:$('#item-description').value.trim()||null,notes:$('#item-notes').value.trim()||null,stackable:$('#item-stackable').value==='true',max_stack:Math.max(1,Number($('#item-max-stack').value)||1),grid_width:Math.max(1,Number($('#item-grid-width').value)||1),grid_height:Math.max(1,Number($('#item-grid-height').value)||1),can_rotate:$('#item-can-rotate').value==='true',pocket_eligible:$('#item-pocket-eligible').value==='true',is_backpack:$('#item-is-backpack').value==='true',backpack_columns:$('#item-is-backpack').value==='true'?Math.max(1,Number($('#item-backpack-columns').value)||4):null,backpack_rows:$('#item-is-backpack').value==='true'?Math.max(1,Number($('#item-backpack-rows').value)||4):null};bonusFields.forEach(k=>payload[`${k}_bonus`]=Number($(`#bonus-${k}`).value)||0);const {error}=id?await window.DND.client.from('items').update(payload).eq('id',id):await window.DND.client.from('items').insert(payload);if(error)throw error;if(selectedFile&&originalImageUrl&&originalImageUrl!==imageUrl)await removeOldObject(originalImageUrl);window.DND.toast(`${payload.name} saved.`,'success');closeEditor();await load()}catch(error){window.DND.toast(error.message||'Item could not be saved.','error');setValidation(error.message||'Upload or save failed.','error')}finally{saveButton.disabled=false;saveButton.textContent='Save Item'}}
  async function remove(){const id=$('#item-id').value,item=items.find(x=>x.id===id);if(!id||!item)return;const confirmed=await window.DNDModal.confirm({type:'danger',kicker:'Item Catalog',title:'Delete Item',message:`Delete ${item.name}? This will fail if the Item is still referenced by Inventory or Equipment.`,confirmText:'Delete Item',cancelText:'Cancel',focusCancel:true});if(!confirmed)return;const {error}=await window.DND.client.from('items').delete().eq('id',id);if(error){window.DND.toast(error.message,'error');return}await removeOldObject(item.image_url);window.DND.toast(`${item.name} deleted.`,'success');closeEditor();await load()}

  window.addEventListener('dnd:navigation-ready',async event=>{if(!event.detail.isAdmin){$('#catalog-denied').hidden=false;return}$('#catalog-main').hidden=false;$('#allowed-slot-list').innerHTML=slots.map(s=>`<label><input type="checkbox" value="${s}" data-allowed-slot>${s}</label>`).join('');await load();$('#catalog-list').addEventListener('click',e=>{const b=e.target.closest('[data-edit-item]');if(b)openEditor(items.find(i=>i.id===b.dataset.editItem))});$('#catalog-new').addEventListener('click',()=>openEditor());$('#catalog-refresh').addEventListener('click',load);$('#catalog-search').addEventListener('input',render);$('#catalog-type').addEventListener('change',render);$('#catalog-setup').addEventListener('change',render);$('#catalog-form').addEventListener('submit',save);$('#catalog-delete').addEventListener('click',remove);$('#catalog-cancel').addEventListener('click',closeEditor);$('#editor-close').addEventListener('click',closeEditor);$('#item-name').addEventListener('input',()=>{if(!$('#item-id').value&&!$('#item-key').value)$('#item-key').value=slug($('#item-name').value);updatePreview()});$('#catalog-form').addEventListener('input',updatePreview);$('#catalog-form').addEventListener('change',updatePreview);$('#item-is-backpack').addEventListener('change',()=>{const yes=$('#item-is-backpack').value==='true';$('#backpack-size-fields').hidden=!yes;if(yes){$('#item-type').value='Backpack';$('#item-slot').value='Backpack';const box=document.querySelector('[data-allowed-slot][value="Backpack"]');if(box)box.checked=true}});
    const zone=$('#item-upload-zone'),input=$('#item-image-file');$('#choose-item-image').addEventListener('click',e=>{e.stopPropagation();input.click()});zone.addEventListener('click',e=>{if(!e.target.closest('button'))input.click()});zone.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();input.click()}});input.addEventListener('change',()=>inspectFile(input.files?.[0]));['dragenter','dragover'].forEach(name=>zone.addEventListener(name,e=>{e.preventDefault();zone.classList.add('drag-active')}));['dragleave','drop'].forEach(name=>zone.addEventListener(name,e=>{e.preventDefault();zone.classList.remove('drag-active')}));zone.addEventListener('drop',e=>inspectFile(e.dataTransfer.files?.[0]));$('#remove-item-image').addEventListener('click',()=>{clearObjectUrl();selectedFile=null;selectedFileInfo=null;$('#item-image').value='';$('#upload-preview').hidden=true;$('#upload-placeholder').hidden=false;$('#remove-item-image').hidden=true;setValidation('Image removed from this draft. Save the Item to remove the stored reference.','warning');updatePreview()});
  },{once:true});
})();
