(() => {
  const $=s=>document.querySelector(s),esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
  const slots=['Head','Neck','Chest','Hands','Legs','Feet','Main Hand','Off Hand','Ring 1','Ring 2','Artifact'];
  const bonusFields=['strength','dexterity','constitution','intelligence','wisdom','charisma','hp','mana'];
  let items=[];
  const hasBonuses=i=>bonusFields.some(k=>Number(i[`${k}_bonus`])!==0);
  const incomplete=i=>!i.item_key||!i.name||(!i.equip_slot&&['weapon','armor'].includes(String(i.item_type).toLowerCase()))||!i.description;
  const slug=s=>String(s||'').trim().toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
  function checkedSlots(){return [...document.querySelectorAll('[data-allowed-slot]:checked')].map(x=>x.value)}
  function updateSummary(){ $('#catalog-total').textContent=items.length;$('#catalog-equippable').textContent=items.filter(i=>i.equip_slot||(i.allowed_slots||[]).length).length;$('#catalog-bonuses').textContent=items.filter(hasBonuses).length;$('#catalog-incomplete').textContent=items.filter(incomplete).length }
  function render(){const search=$('#catalog-search').value.trim().toLowerCase(),type=$('#catalog-type').value.toLowerCase(),setup=$('#catalog-setup').value;const rows=items.filter(i=>{const text=[i.name,i.item_key,i.item_type,i.equip_slot].join(' ').toLowerCase();return(!search||text.includes(search))&&(type==='all'||String(i.item_type).toLowerCase()===type)&&(setup==='all'||(setup==='incomplete'?incomplete(i):!incomplete(i)))});$('#catalog-list').innerHTML=rows.length?rows.map(i=>`<button type="button" class="catalog-item ${incomplete(i)?'incomplete':'ready'}" data-edit-item="${i.id}">${i.image_url?`<img src="${esc(i.image_url)}" alt="">`:'<span>◇</span>'}<div><strong>${esc(i.name)}</strong><small>${esc(i.rarity||'Common')} • ${esc(i.item_type||'Item')}${i.equip_slot?` • ${esc(i.equip_slot)}`:''}</small><em>${incomplete(i)?'Needs Setup':hasBonuses(i)?'Ready • Bonuses Defined':'Ready'}</em></div></button>`).join(''):'<p class="catalog-empty">No Items match these filters.</p>'}
  async function load(){const {data,error}=await window.DND.client.from('items').select('*').order('name');if(error){$('#catalog-list').innerHTML=`<p class="catalog-error">${esc(error.message)}</p>`;return}items=data||[];updateSummary();render()}
  function updatePreview(){const name=$('#item-name').value||'Item Preview',rarity=$('#item-rarity').value,type=$('#item-type').value,slot=$('#item-slot').value,image=$('#item-image').value.trim();$('#editor-preview-name').textContent=name;$('#editor-preview-meta').textContent=[rarity,type,slot].filter(Boolean).join(' • ');$('#editor-image-preview').src=image||'../../assets/images/shared/character-placeholder.png';const effects=[];[['STR','strength'],['DEX','dexterity'],['CON','constitution'],['INT','intelligence'],['WIS','wisdom'],['CHA','charisma'],['HP','hp'],['Mana','mana']].forEach(([label,key])=>{const value=Number($(`#bonus-${key}`).value)||0;if(value)effects.push(`<span>${label} <b>${value>0?'+':''}${value}</b></span>`)});$('#editor-preview-effects').innerHTML=effects.length?effects.join(''):'<small>No bonuses defined.</small>'}
  function openEditor(item=null){$('#catalog-form').hidden=false;$('#editor-title').textContent=item?'Edit Item':'Create Item';$('#item-id').value=item?.id||'';$('#item-name').value=item?.name||'';$('#item-key').value=item?.item_key||'';$('#item-rarity').value=item?.rarity||'Common';$('#item-type').value=item?.item_type||'Item';$('#item-slot').value=item?.equip_slot||'';$('#item-image').value=item?.image_url||'';$('#item-stackable').value=String(Boolean(item?.stackable));$('#item-max-stack').value=item?.max_stack||1;$('#item-description').value=item?.description||'';$('#item-notes').value=item?.notes||'';bonusFields.forEach(k=>$(`#bonus-${k}`).value=item?.[`${k}_bonus`]||0);document.querySelectorAll('[data-allowed-slot]').forEach(x=>x.checked=(item?.allowed_slots||[]).includes(x.value));$('#catalog-delete').hidden=!item;updatePreview();$('#catalog-form').scrollIntoView({behavior:'smooth',block:'start'})}
  function closeEditor(){$('#catalog-form').hidden=true}
  async function save(e){e.preventDefault();const id=$('#item-id').value,payload={name:$('#item-name').value.trim(),item_key:slug($('#item-key').value||$('#item-name').value),rarity:$('#item-rarity').value,item_type:$('#item-type').value,equip_slot:$('#item-slot').value||null,allowed_slots:checkedSlots(),image_url:$('#item-image').value.trim()||null,description:$('#item-description').value.trim()||null,notes:$('#item-notes').value.trim()||null,stackable:$('#item-stackable').value==='true',max_stack:Math.max(1,Number($('#item-max-stack').value)||1)};bonusFields.forEach(k=>payload[`${k}_bonus`]=Number($(`#bonus-${k}`).value)||0);const query=id?window.DND.client.from('items').update(payload).eq('id',id):window.DND.client.from('items').insert(payload);const {error}=await query;if(error){window.DND.toast(error.message,'error');return}window.DND.toast(`${payload.name} saved.`,'success');closeEditor();await load()}
  async function remove(){const id=$('#item-id').value,item=items.find(x=>x.id===id);if(!id||!item)return;const confirmed=await window.DNDModal.confirm({type:'danger',kicker:'Item Catalog',title:'Delete Item',message:`Delete ${item.name}? This will fail if the Item is still referenced by Inventory or Equipment.`,confirmText:'Delete Item',cancelText:'Cancel',focusCancel:true});if(!confirmed)return;const {error}=await window.DND.client.from('items').delete().eq('id',id);if(error){window.DND.toast(error.message,'error');return}window.DND.toast(`${item.name} deleted.`,'success');closeEditor();await load()}
  window.addEventListener('dnd:navigation-ready',async event=>{if(!event.detail.isAdmin){$('#catalog-denied').hidden=false;return}$('#catalog-main').hidden=false;$('#allowed-slot-list').innerHTML=slots.map(s=>`<label><input type="checkbox" value="${s}" data-allowed-slot>${s}</label>`).join('');await load();$('#catalog-list').addEventListener('click',e=>{const b=e.target.closest('[data-edit-item]');if(b)openEditor(items.find(i=>i.id===b.dataset.editItem))});$('#catalog-new').addEventListener('click',()=>openEditor());$('#catalog-refresh').addEventListener('click',load);$('#catalog-search').addEventListener('input',render);$('#catalog-type').addEventListener('change',render);$('#catalog-setup').addEventListener('change',render);$('#catalog-form').addEventListener('submit',save);$('#catalog-delete').addEventListener('click',remove);$('#catalog-cancel').addEventListener('click',closeEditor);$('#editor-close').addEventListener('click',closeEditor);$('#item-name').addEventListener('input',()=>{if(!$('#item-id').value&&!$('#item-key').value)$('#item-key').value=slug($('#item-name').value);updatePreview()});$('#catalog-form').addEventListener('input',updatePreview);$('#catalog-form').addEventListener('change',updatePreview)},{once:true});
})();
