(() => {
 const q=s=>document.querySelector(s), esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
 const characterId=new URLSearchParams(location.search).get('id');
 const slots=['Head','Neck','Chest','Hands','Legs','Feet','Main Hand','Off Hand','Ring 1','Ring 2','Artifact'];
 const cols={'Head':'head_item_id','Neck':'neck_item_id','Chest':'chest_item_id','Hands':'hands_item_id','Legs':'legs_item_id','Feet':'feet_item_id','Main Hand':'main_hand_item_id','Off Hand':'off_hand_item_id','Ring 1':'ring_1_item_id','Ring 2':'ring_2_item_id','Artifact':'artifact_item_id'};
 let character, owner=false, inventory=[], equipment={}, dragged=null, activeFilter='all';
 const site=p=>window.DND?.siteUrl?window.DND.siteUrl(p):`/${p.replace(/^\//,'')}`;
 function infer(name=''){const n=name.toLowerCase();if(/tonic|elixir|draught|flask|vial/.test(n))return{type:'Consumable',slot:null,allowed:[]};if(/armor|robe|leather|harness|garment|warplate/.test(n))return{type:'Armor',slot:'Chest',allowed:['Chest']};if(/cloak|mantle/.test(n))return{type:'Armor',slot:'Neck',allowed:['Neck']};if(/shield/.test(n))return{type:'Weapon',slot:'Off Hand',allowed:['Off Hand']};if(/ring/.test(n))return{type:'Armor',slot:'Ring 1',allowed:['Ring 1','Ring 2']};if(/staff|axe|spear|bow|blade|seax|knife|harp|drum|crook/.test(n))return{type:'Weapon',slot:'Main Hand',allowed:['Main Hand','Off Hand']};if(/sigil|core|totem|prism|reliquary/.test(n))return{type:'Quest',slot:'Artifact',allowed:['Artifact']};return{type:'Quest',slot:null,allowed:[]}}
 async function fetchJson(path){const r=await fetch(encodeURI(site(path)),{cache:'no-cache'});if(!r.ok)throw Error(path);return r.json()}
 async function syncStarter(){if(!owner)return;try{const m=await fetchJson('assets/classes/viking/classes.json');let found;for(const cid of m.classes||[]){const c=await fetchJson(`assets/classes/viking/${cid}/class.json`);for(const hid of c.heroes||[]){const h=await fetchJson(`assets/classes/viking/${cid}/${hid}/${hid}.json`);if((h.name||'').toLowerCase()===(character.race||'').toLowerCase()||(hid===String(character.race||'').toLowerCase().replaceAll(' ','-'))){found={c,h,hid};break}}if(found)break}if(!found)return;const rows=(found.h.starterEquipment||[]).map(x=>{const i=infer(x.name);return{id:x.id,name:x.name,quantity:x.quantity||1,item_type:i.type,equip_slot:x.equipSlot||i.slot,allowed_slots:x.allowedSlots||i.allowed,image_url:site(`assets/classes/viking/${found.c.id}/${found.hid}/${x.icon}`),description:x.description||'',notes:x.notes||'',stackable:i.type==='Consumable',max_stack:i.type==='Consumable'?99:1}});await window.DND.client.rpc('sync_character_starter_items',{p_character_id:characterId,p_items:rows})}catch(e){console.warn('Starter item sync skipped',e)}}
 async function load(){const [{data:c},{data:inv,error:ie},{data:eq}]=await Promise.all([window.DND.client.from('characters').select('*').eq('id',characterId).maybeSingle(),window.DND.client.from('inventory').select('id,quantity,items(*)').eq('character_id',characterId),window.DND.client.from('character_equipment').select('*').eq('character_id',characterId).maybeSingle()]);character=c;owner=c?.user_id===window.DND.session?.user?.id;if(owner&&(!inv||!inv.length)){await syncStarter();const r=await window.DND.client.from('inventory').select('id,quantity,items(*)').eq('character_id',characterId);inventory=r.data||[]}else inventory=ie?[]:(inv||[]);equipment=eq||{};renderAll()}
 function allowed(item){const a=item.allowed_slots?.length?item.allowed_slots:(item.equip_slot?[item.equip_slot]:[]);return a}
 function isEquipped(id){return slots.some(s=>equipment[cols[s]]===id)}
 function renderInventory(){const rows=activeFilter==='all'?inventory:inventory.filter(r=>(r.items?.item_type||'').toLowerCase().includes(activeFilter));q('#inventory-count').textContent=`${inventory.length} Item${inventory.length===1?'':'s'}`;q('#inventory-grid').innerHTML=rows.length?rows.map(r=>`<button class="inventory-slot-v2 item-system-inventory ${isEquipped(r.items.id)?'is-equipped':''}" draggable="${owner}" data-inventory-id="${r.id}" data-item-id="${r.items.id}" title="${esc(r.items.name)}">${r.items.image_url?`<img src="${esc(r.items.image_url)}" alt="${esc(r.items.name)}">`:'◇'}<b>${r.quantity||1}</b>${isEquipped(r.items.id)?'<i>Equipped</i>':''}</button>`).join(''):'<div class="inventory-empty-v2">No items in this category.</div>'}
 function renderEquipment(){q('#equipment-grid').innerHTML=slots.map(s=>{const id=equipment[cols[s]],row=inventory.find(r=>r.items?.id===id);return `<div class="equipment-slot-v2 item-system-slot ${row?'filled':''}" data-equipment-slot="${s}">${row?`${row.items.image_url?`<img src="${esc(row.items.image_url)}" alt="${esc(row.items.name)}">`:''}<strong>${esc(row.items.name)}</strong><button type="button" data-unequip="${s}" ${owner?'':'hidden'}>×</button>`:`<span>${s}</span>`}</div>`}).join('')}
 function bonuses(){const total={strength_bonus:0,dexterity_bonus:0,constitution_bonus:0,intelligence_bonus:0,wisdom_bonus:0,charisma_bonus:0,hp_bonus:0,mana_bonus:0};slots.forEach(s=>{const row=inventory.find(r=>r.items?.id===equipment[cols[s]]);if(row)Object.keys(total).forEach(k=>total[k]+=Number(row.items[k])||0)});return total}
 function renderStats(){const b=bonuses(),defs=[['STR','Strength','strength','strength_bonus'],['DEX','Dexterity','dexterity','dexterity_bonus'],['CON','Constitution','constitution','constitution_bonus'],['INT','Intelligence','intelligence','intelligence_bonus'],['WIS','Wisdom','wisdom','wisdom_bonus'],['CHA','Charisma','charisma','charisma_bonus']];q('#attribute-list').innerHTML=defs.map(([a,n,k,bk])=>`<div class="sheet-attribute"><span>${a}</span><strong>${(Number(character[k])||0)+b[bk]}</strong>${b[bk]?`<em>+${b[bk]} Equipment</em>`:''}<small>${n}</small></div>`).join('');q('#sheet-hp').innerHTML=`${character.current_hp??0} / ${(Number(character.max_hp)||0)+b.hp_bonus}${b.hp_bonus?`<small>+${b.hp_bonus}</small>`:''}`;q('#sheet-mana').innerHTML=`${character.current_mana??0} / ${(Number(character.max_mana)||0)+b.mana_bonus}${b.mana_bonus?`<small>+${b.mana_bonus}</small>`:''}`}
 function show(row){const i=row.items,b=Object.entries({STR:i.strength_bonus,DEX:i.dexterity_bonus,CON:i.constitution_bonus,INT:i.intelligence_bonus,WIS:i.wisdom_bonus,CHA:i.charisma_bonus,HP:i.hp_bonus,Mana:i.mana_bonus}).filter(([,v])=>Number(v));q('#item-detail').innerHTML=`${i.image_url?`<img src="${esc(i.image_url)}" alt="${esc(i.name)}">`:''}<h3>${esc(i.name)}</h3><p>${esc(i.rarity||'Common')} • ${esc(i.item_type||'Item')}${i.equip_slot?` • ${esc(i.equip_slot)}`:''}</p><p>${esc(i.description||'No item description.')}</p>${b.length?`<div class="item-effects"><h4>Effects</h4>${b.map(([k,v])=>`<span>${k} <b>+${v}</b></span>`).join('')}</div>`:''}<div class="item-notes"><h4>Notes</h4><p>${esc(i.notes||'No item notes have been added.')}</p></div><p>Quantity: ${row.quantity||1}</p>`}
 function renderAll(){renderInventory();renderEquipment();renderStats()}
 async function equip(slot){if(!dragged||!owner)return;const row=inventory.find(r=>r.items?.id===dragged);if(!allowed(row.items).includes(slot))return;const {error}=await window.DND.client.rpc('equip_character_item',{p_character_id:characterId,p_item_id:dragged,p_slot:slot});if(error){window.DND.toast(error.message,'error');return}await load();window.DND.toast(`${row.items.name} equipped to ${slot}.`,'success')}
 function bind(){q('#inventory-grid').addEventListener('click',e=>{const b=e.target.closest('[data-item-id]');if(b)show(inventory.find(r=>r.items.id===b.dataset.itemId))});q('.inventory-filters')?.addEventListener('click',e=>{const b=e.target.closest('[data-filter]');if(!b)return;activeFilter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>x.classList.toggle('active',x===b));renderInventory()});q('#inventory-grid').addEventListener('dragstart',e=>{const b=e.target.closest('[data-item-id]');if(!b||!owner)return;e.stopPropagation();dragged=b.dataset.itemId;q('#equipment-grid').classList.add('dragging');const row=inventory.find(r=>r.items.id===dragged);document.querySelectorAll('[data-equipment-slot]').forEach(s=>s.classList.toggle('valid-drop',allowed(row.items).includes(s.dataset.equipmentSlot)))});document.addEventListener('dragend',()=>{dragged=null;q('#equipment-grid')?.classList.remove('dragging');document.querySelectorAll('[data-equipment-slot]').forEach(s=>s.classList.remove('valid-drop','drag-over'))});q('#equipment-grid').addEventListener('dragover',e=>{const s=e.target.closest('[data-equipment-slot]');if(s?.classList.contains('valid-drop')){e.preventDefault();s.classList.add('drag-over')}});q('#equipment-grid').addEventListener('dragleave',e=>e.target.closest('[data-equipment-slot]')?.classList.remove('drag-over'));q('#equipment-grid').addEventListener('drop',e=>{const s=e.target.closest('[data-equipment-slot]');if(s){e.preventDefault();equip(s.dataset.equipmentSlot)}});q('#equipment-grid').addEventListener('click',async e=>{const u=e.target.closest('[data-unequip]');if(u){const {error}=await window.DND.client.rpc('unequip_character_slot',{p_character_id:characterId,p_slot:u.dataset.unequip});if(error)window.DND.toast(error.message,'error');else await load();return}const s=e.target.closest('[data-equipment-slot]');if(s){const row=inventory.find(r=>r.items.id===equipment[cols[s.dataset.equipmentSlot]]);if(row)show(row)}})}
 window.addEventListener('dnd:navigation-ready',()=>{const wait=setInterval(()=>{if(q('#character-sheet')&&!q('#character-sheet').hidden){clearInterval(wait);bind();load()}},100)},{once:true});
})();
